server:
  port: 8082
spring:
  application:
    name: netdisk-service-notice # 服务名称
  profiles:
    active: dev

netdisk:
  swagger:
    title: 公告接口文档
    description: 公告接口文档
    package: top.linrty.netdisk.notice.controller # 扫描的包路径
  dbname: netdisk_notice



